In [10]:
import pandas as pd

In [11]:
path = r"C:\Users\Stanisław\Desktop\Programowanie\GitHub\PL_predictions\epl_predictions\data\raw\previous_tables.csv"

df = pd.read_csv(path)

In [12]:
df

,Rk,Squad,MP,W,D,L,GF,GA,GD,Pts,Pts/MP,Attendance,Top Team Scorer,Goalkeeper,Notes,Season,xG,xGA,xGD,xGD/90
0,1,Manchester Utd,38,25,7,6,73,35,38,82,2.16,"41,681",Eric Cantona - 14,Peter Schmeichel,→ Champions League via league finish,1995-1996,NaN,NaN,NaN,NaN
1,2,Newcastle Utd,38,24,6,8,66,37,29,78,2.05,"36,505",Les Ferdinand - 25,Shaka Hislop,→ UEFA Cup via league finish,1995-1996,NaN,NaN,NaN,NaN
2,3,Liverpool,38,20,11,7,70,34,36,71,1.87,"39,553",Robbie Fowler - 28,David James,→ UEFA Cup Winners' Cup via cup win 1,1995-1996,NaN,NaN,NaN,NaN
3,4,Aston Villa,38,18,9,11,52,35,17,63,1.66,"32,772",Dwight Yorke - 17,Mark Bosnich,→ UEFA Cup via league finish,1995-1996,NaN,NaN,NaN,NaN
4,5,Arsenal,38,17,12,9,49,32,17,63,1.66,"37,568",Ian Wright - 15,David Seaman,→ UEFA Cup via league finish 2,1995-1996,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
575,16,Brentford,38,10,9,19,56,65,-9,39,1.03,"17,082",Yoane Wissa - 12,Mark Flekken,NaN,2023-2024,58.2,56.0,2.2,0.06
576,17,Nott'ham Forest,38,9,9,20,49,67,-18,32,0.84,"29,386",Chris Wood - 14,Matt Turner,4-point deduction 2,2023-2024,49.9,53.2,-3.3,-0.09
577,18,Luton Town,38,6,8,24,52,85,-33,26,0.68,"11,240",Carlton Morris - 11,Thomas Kaminski,Relegated,2023-2024,42.4,78.0,-35.5,-0.94
578,19,Burnley,38,5,9,24,41,78,-37,24,0.63,"21,184",Jacob Bruun Larsen - 6,James Trafford,Relegated,2023-2024,40.6,70.4,-29.7,-0.78
579,20,Sheffield Utd,38,3,7,28,35,104,-69,16,0.42,"30,011","Oliver McBurnie, Ben Brereton - 6",Wes Foderingham,Relegated,2023-2024,38.3,76.7,-38.4,-1.01